require('config.alpha')
require('config.lightspeed')
require('config.web-devicons')
require('config.bufferline')
require('config.nvimtree')
require('config.scope')
require('config.nvim-cmp')
require('config.nvim-lspconfig')
